### ISSUE TITLE
ReactSkia quit unexpactedly (Scheduler)

### ISSUE THREAD

**Issue by Taym95** [react-native-skia/react-native-skia#1]
Hi @Kudo, Thank a lot for the great work, I would like to help and contribute on this repo, as a start I see an `Assertion failed` after the user closes the app, the error comes from Scheduler destructor:

`Assertion failed: (surfaceIds.empty() && "Scheduler was destroyed with outstanding Surfaces."), function ~Scheduler, file ReactCommon/react/renderer/scheduler/Scheduler.cpp, line 146.`

Do you have an idea what can be the problem?

**Comment by Kudo** [comment]
Hey @Taym95, thank you for participating.
I saw this messages multiple times and just ignoring this before 😅

The root cause should relate to abnormal exiting for Fabric.
During Fabric `Scheduler::~Scheduler` called, all surfaces should be unregistered before.
In react-react-skia, simply because I called `Scheduler::startSurface` but without corresponding `Scheduler::stopSurface`.
